### ISSUE TITLE
 Select network

### ISSUE THREAD

**Issue by MoMannn** [0xcert/erc721-validator-api#4]
Currently the deployed validator only works for main net. Please add options to run on other networks and add a dropdown / radio box selector for at least ROPSTEN and RINKSBY.

**Comment by MoMannn** [comment]
Which network should we support? 
rinkeby, ropsten, mainnet, avalanche? polygon? binance? fantom? moonriver? testnets? 

@fulldecent

**Comment by xpepermint** [comment]
All ETH for now.

**Comment by MoMannn** [comment]
Done. We can now pretty simply add other networks as well.

**Comment by fulldecent** [comment]
Awesome, thank you!
