### ISSUE TITLE
Question About Usuage.

### ISSUE THREAD

**Issue by aacostarua** [0xcert/erc721-validator-api#7]
Can this be used to query all ERC721's with ethereum, contract address, token ID, imageURL & metadata on a given network.  Similiar to the a way  https://opensea-api.herokuapp.com/assets/?format=api&limit=100&order_by=auction_created_date&order_direction=desc&owner= currently works?

Thanks.

**Comment by MoMannn** [comment]
We can validate any kind of erc721 token, using contract address and tokenId. We are not validating or checking offchain metadata only that onchain contract is a valid erc721.
