### ISSUE TITLE
Homestead glitches

### ISSUE THREAD

**Issue by fulldecent** [0xcert/erc721-validator-api#9]
I'm not sure which fork or breaking Infura/web3 broke this. But currently the validator is down.

<img width="1374" alt="Screen Shot 2021-09-13 at 21 10 46" src="https://user-images.githubusercontent.com/382183/133178128-05f58213-e894-4908-8999-8dd0744b6d41.png">

**Comment by xpepermint** [comment]
Fixed in the latest verson.
